services:
  - type: web
    name: privacy_analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app.server
    autoDeploy: true
